/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import control.DatabaseController;
import java.util.HashMap;
import java.util.Map;
/**
 *
 * @author MARCUS VINICIUS
 */
public class PerformLeftJoinOperationScreen extends javax.swing.JFrame {

    /**
     * Creates new form PerformInnerJoinOperation
     */
    public PerformLeftJoinOperationScreen() {
        initComponents();
        changeButtonEnabled();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sourceTableCombo = new javax.swing.JComboBox<>();
        queryLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        relatedTablesCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Perform Left Join Operation");

        jLabel1.setText("Source Table (LEFT)");

        sourceTableCombo.setModel(new javax.swing.DefaultComboBoxModel<>(dc.getTablesName()));
        sourceTableCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceTableComboActionPerformed(evt);
            }
        });
        sourceTableCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sourceTableComboItemStateChanged(evt);
            }
        });
        sourceTableCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceTableComboActionPerformed(evt);
            }
        });

        jButton1.setText("Perform Left Join");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Table Related");

        relatedTablesCombo.setModel(new javax.swing.DefaultComboBoxModel<>(dc.getRelatedTables(this.sourceTableCombo.getSelectedItem().toString())));
        relatedTablesCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatedTablesComboActionPerformed(evt);
            }
        });
        relatedTablesCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatedTablesComboActionPerformed(evt);
            }
        });
        relatedTablesCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatedTablesComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(queryLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(relatedTablesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sourceTableCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jButton1)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(sourceTableCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(relatedTablesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(queryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sourceTableComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceTableComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sourceTableComboActionPerformed

    
    public void changeRelatedTablesInCombo(){
        this.relatedTablesCombo.removeAllItems();
        this.relatedTablesCombo.setModel(new javax.swing.DefaultComboBoxModel<>(dc.getRelatedTables(this.sourceTableCombo.getSelectedItem().toString())));
        changeButtonEnabled();
    }
    
    public void changeButtonEnabled(){
        if (this.relatedTablesCombo.getItemCount()<1) this.jButton1.setEnabled(false);
        else this.jButton1.setEnabled(true);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HashMap<String, String> columnsName=dc.getRelatedColumnsName(this.sourceTableCombo.getSelectedItem().toString());
        String queryText="SELECT COUNT(*) FROM "+this.sourceTableCombo.getSelectedItem().toString()+" LEFT JOIN "+relatedTablesCombo.getSelectedItem().toString()+" ON ";
        int n=0;
        for (Map.Entry<String, String> entry : columnsName.entrySet()){
            if (n>0) queryText+=" AND ";
            queryText+=entry.getKey()+"="+entry.getValue();
            ++n;
        }
        queryLabel.setText(queryText);
        pack();
        repaint();
        DatabaseController dc= new DatabaseController();
        long init, end, difference;
        init = System.currentTimeMillis();
        int total=dc.performLeftJoin(this.sourceTableCombo.getSelectedItem().toString(), this.relatedTablesCombo.getSelectedItem().toString());
        end = System.currentTimeMillis(); 
        difference=end-init;
        javax.swing.JOptionPane.showMessageDialog(this,"The search has found "+total+" records in "+(difference / 1000)+" seconds","Result",javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void relatedTablesComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatedTablesComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relatedTablesComboActionPerformed

    private void sourceTableComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sourceTableComboItemStateChanged
        // TODO add your handling code here:
        changeRelatedTablesInCombo();
    }//GEN-LAST:event_sourceTableComboItemStateChanged

    private DatabaseController dc= new DatabaseController();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel queryLabel;
    private javax.swing.JComboBox<String> relatedTablesCombo;
    private javax.swing.JComboBox<String> sourceTableCombo;
    // End of variables declaration//GEN-END:variables
}
