/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import control.DatabaseController;
import control.Helper;
import java.util.HashMap;
import java.util.Map;
/**
 *
 * @author MARCUS VINICIUS
 */
public class PerformBatteryTestingScreen extends javax.swing.JFrame {

    /**
     * Creates new form PerformInnerJoinOperation
     */
    public PerformBatteryTestingScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        sourceTableCombo = new javax.swing.JComboBox<>();
        queryLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nTestsTxt = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Perform Battery of Tests");

        jLabel1.setText("Table");

        sourceTableCombo.setModel(new javax.swing.DefaultComboBoxModel<>(dc.getTablesName()));
        sourceTableCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceTableComboActionPerformed(evt);
            }
        });
        sourceTableCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sourceTableComboItemStateChanged(evt);
            }
        });
        sourceTableCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceTableComboActionPerformed(evt);
            }
        });

        jButton1.setText("Perform Inner Join");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Number of Tests");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(queryLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nTestsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sourceTableCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sourceTableCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(nTestsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(queryLabel)
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sourceTableComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceTableComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sourceTableComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        long init, end, difference;
        
        if (!Helper.isStringNumeric(this.nTestsTxt.getText())){
            javax.swing.JOptionPane.showMessageDialog(this,"The number of tests must be a numeric value","Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        int n=Integer.parseInt(this.nTestsTxt.getText());
        if (n<=0){
            javax.swing.JOptionPane.showMessageDialog(this,"The number must be greater than 0","Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        init = System.currentTimeMillis();
        int total=dc.runTestsRandomly(this.sourceTableCombo.getSelectedItem().toString(), n);
        end = System.currentTimeMillis(); 
        difference=end-init;
        javax.swing.JOptionPane.showMessageDialog(this,"The search has found "+total+" records in "+(difference / 1000)+" seconds for "+n+" tests","Result",javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sourceTableComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sourceTableComboItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_sourceTableComboItemStateChanged

    private DatabaseController dc= new DatabaseController();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nTestsTxt;
    private javax.swing.JLabel queryLabel;
    private javax.swing.JComboBox<String> sourceTableCombo;
    // End of variables declaration//GEN-END:variables
}
