/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import control.DatabaseController;
import java.util.HashMap;
import java.util.Map;
/**
 *
 * @author MARCUS VINICIUS
 */
public class PerformInnerJoinOperationWithNonPrimaryKeysScreen extends javax.swing.JFrame {

    /**
     * Creates new form PerformInnerJoinOperation
     */
    public PerformInnerJoinOperationWithNonPrimaryKeysScreen() {
        initComponents();
        changeButtonEnabled();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sourceTableCombo = new javax.swing.JComboBox<>();
        queryLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        relatedTablesCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        columnsSourceTableCombo = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        columnsRelatedTableCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Perform Inner Join Operation");

        jLabel1.setText("Source Table");

        sourceTableCombo.setModel(new javax.swing.DefaultComboBoxModel<>(dc.getTablesName()));
        sourceTableCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceTableComboActionPerformed(evt);
            }
        });
        sourceTableCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceTableComboActionPerformed(evt);
            }
        });

        jButton1.setText("Perform Inner Join");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Table Related");

        relatedTablesCombo.setModel(new javax.swing.DefaultComboBoxModel<>(dc.getRelatedTables(this.sourceTableCombo.getSelectedItem().toString())));
        relatedTablesCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatedTablesComboActionPerformed(evt);
            }
        });
        relatedTablesCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatedTablesComboActionPerformed(evt);
            }
        });
        relatedTablesCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatedTablesComboActionPerformed(evt);
            }
        });

        jLabel3.setText("Choose Column from Source Table");

        columnsSourceTableCombo.setModel(new javax.swing.DefaultComboBoxModel<>(dc.getColumnsByTablename(this.sourceTableCombo.getSelectedItem().toString())));
        columnsSourceTableCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnsSourceTableComboActionPerformed(evt);
            }
        });

        jLabel4.setText("Choose Column from Related Table");

        columnsRelatedTableCombo.setModel(new javax.swing.DefaultComboBoxModel<>(dc.getColumnsByTablename(this.relatedTablesCombo.getSelectedItem().toString())));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(columnsSourceTableCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(sourceTableCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(relatedTablesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(columnsRelatedTableCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 163, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(queryLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(sourceTableCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(columnsSourceTableCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relatedTablesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(columnsRelatedTableCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(queryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sourceTableComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceTableComboActionPerformed
        // TODO add your handling code here:
        this.columnsSourceTableCombo.setModel(new javax.swing.DefaultComboBoxModel<>(dc.getColumnsByTablename(this.sourceTableCombo.getSelectedItem().toString())));
        changeRelatedTablesInCombo();
        
    }//GEN-LAST:event_sourceTableComboActionPerformed

    
    public void changeRelatedTablesInCombo(){
        this.relatedTablesCombo.removeAllItems();
        this.relatedTablesCombo.setModel(new javax.swing.DefaultComboBoxModel<>(dc.getRelatedTables(this.sourceTableCombo.getSelectedItem().toString())));
        columnsRelatedTableCombo.setModel(new javax.swing.DefaultComboBoxModel<>(dc.getColumnsByTablename(this.relatedTablesCombo.getSelectedItem().toString())));
        changeButtonEnabled();
    }
    
    public void changeButtonEnabled(){
        if (this.relatedTablesCombo.getItemCount()<1) this.jButton1.setEnabled(false);
        else this.jButton1.setEnabled(true);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String queryText="SELECT COUNT(*) FROM "+this.sourceTableCombo.getSelectedItem().toString()+" INNER JOIN "+relatedTablesCombo.getSelectedItem().toString()+" ON "+this.sourceTableCombo.getSelectedItem().toString()+"="+this.relatedTablesCombo.getSelectedItem().toString();
        queryLabel.setText(queryText);
        pack();
        long init, end, difference;
        init = System.currentTimeMillis();
        int total=dc.performInnerJoin(this.sourceTableCombo.getSelectedItem().toString(), this.columnsSourceTableCombo.getSelectedItem().toString(), this.relatedTablesCombo.getSelectedItem().toString(), this.columnsRelatedTableCombo.getSelectedItem().toString());
        end = System.currentTimeMillis(); 
        difference=end-init;
        javax.swing.JOptionPane.showMessageDialog(this,"The search has found "+total+" records in "+(difference / 1000)+" seconds","Result",javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void relatedTablesComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatedTablesComboActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_relatedTablesComboActionPerformed

    private void columnsSourceTableComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnsSourceTableComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_columnsSourceTableComboActionPerformed

    private DatabaseController dc= new DatabaseController();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> columnsRelatedTableCombo;
    private javax.swing.JComboBox<String> columnsSourceTableCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel queryLabel;
    private javax.swing.JComboBox<String> relatedTablesCombo;
    private javax.swing.JComboBox<String> sourceTableCombo;
    // End of variables declaration//GEN-END:variables
}
